#!/bin/bash

USER=$(whoami)
HOST=$(hostname)

cd /usr/local/src/logs

rm alltty.$HOST.$USER
touch alltty.$HOST.$USER

find . -name "ttylog.$HOST.$USER.*" > ~/.logfiles
while read logfile; do
	rm $logfile
	touch $logfile
done <~/.logfiles
rm ~/.logfiles

cd $USER

